### ISSUE TITLE
colors in kitty

### ISSUE THREAD

**Issue by euglevi** [pineapplegiant/spaceduck-terminal#5]
The colors for kitty did not work out well with me. The white was dark purple, and so on. Also I did not like blue being cyan and cyan being purple. I have figured out a combination that I prefer but I leave you to judge it.

```
background #0f111b 
foreground #ecf0c1
cursor #ecf0c1
selection_background #686f9a
selection_foreground #ffffff
color0  #000000
color8  #c1c3cc
color16 #30365F
color1  #e33400
color9  #e33400
color2  #5ccc96
color10 #5ccc96
color3  #f2ce00
color11 #f2ce00
color4  #7a5ccc
color12 #b3a1e6
color5  #b3a1e6
color13 #ce6f8f
color6  #00a3cc
color14 #00a3cc
color7  #ecf0c1
color15 #ffffff
````

**Comment by pineapplegiant** [comment]
Can you include a screenshot of your terminal as I do not use Kitty? I've mentioned in other issues that I've moved colors in my terminal theme for aesthetics, yes.

**Comment by euglevi** [comment]
For example, below is a screenshot of Mutt without any custom color I now have. Before, all lines were dark purple so that it was impossible to read them. I get that this really depends on aesthetics and almost each app allows for customization: it is not really a bug I'm pointing at. It is just that I found it confusing when customizing apps that white was purple and yellow was something else completely. Thank you for the colors, I find it a very nice color scheme!

![2021-05-04_09-48](https://user-images.githubusercontent.com/58224469/116974427-6a2c8b80-acbe-11eb-87be-118f111e7afb.png)

**Comment by YoussefBouzekri** [comment]
@euglevi The colors have been swapped on purpose, check this PR #1
